// Чистые хелперы (без DOM, без Vue) — URL-склейка, парсинг имён, сборка gallery.ts.

import type { GalleryEntry, SizeTag } from './types'

export const SIZE_TAGS: SizeTag[] = ['S', 'M', 'L', '1000']

// Склейка base + filename. Терпим к лишнему/недостающему слэшу на конце base.
export const joinUrl = (base: string, file: string): string => {
  if (!base) return file
  const b = base.trim()
  if (!b) return file
  return b.endsWith('/') ? b + file : b + '/' + file
}

// Зеркало raw.githubusercontent.com → cdn.jsdelivr.net.
// Нужно если Vue-компонент встраивается в среду со строгим CSP, который
// блокирует загрузку картинок с raw.githubusercontent.com.
// В обычном VitePress-сайте это не нужно — но и не мешает.
export const toDisplayUrl = (url: string): string => {
  if (!url) return url
  const m = url.match(/^https:\/\/raw\.githubusercontent\.com\/([^/]+)\/([^/]+)\/([^/]+)\/(.+)$/)
  if (m) {
    const [, user, repo, branch, path] = m
    return `https://cdn.jsdelivr.net/gh/${user}/${repo}@${branch}/${path}`
  }
  return url
}

// Парсинг textarea с именами файлов. Разделители: перевод строки, запятая, точка с запятой.
export const parseFilenames = (text: string): string[] =>
  text.split(/[\r\n,;]+/).map(s => s.trim()).filter(Boolean)

// Создание новой пустой записи галереи.
export const makeEntry = (filename: string, baseUrl: string): GalleryEntry => ({
  filename,
  url: joinUrl(baseUrl, filename),
  rooms: [],
  models: [],
  woods: [],
  zones: [],
  sizes: [],
  note: '',
  tagged: false,
})

// Сколько из 4 главных категорий заполнено: комната, модель, дерево, зона.
// Размер и заметка не считаются — они опциональные.
export const countCritical = (e: GalleryEntry): number => {
  let c = 0
  if (e.rooms.length)  c++
  if (e.models.length) c++
  if (e.woods.length)  c++
  if (e.zones.length)  c++
  return c
}

// Иммутабельный toggle элемента в массиве.
export const toggleIn = <T,>(arr: T[], value: T): T[] => {
  const i = arr.indexOf(value)
  if (i === -1) return [...arr, value]
  const next = arr.slice()
  next.splice(i, 1)
  return next
}

// Скачивание файла через Blob + objectURL.
export const downloadFile = (
  name: string,
  content: string,
  type = 'text/plain;charset=utf-8',
): boolean => {
  try {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = name
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    setTimeout(() => URL.revokeObjectURL(url), 1000)
    return true
  } catch {
    return false
  }
}

// Копирование строки в буфер. Возвращает успех.
export const copyText = async (text: string): Promise<boolean> => {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    return false
  }
}

// Сборка gallery.ts по спецификации из ТЗ. На вход — все записи,
// в файл попадают только tagged: true.
export const buildGalleryTs = (entries: GalleryEntry[]): string => {
  const tagged = entries.filter(e => e.tagged)
  const L: string[] = []
  L.push('// data/gallery.ts — auto-generated by Gallery Tagger')
  L.push(`// Generated: ${new Date().toISOString()}`)
  L.push(`// Tagged entries: ${tagged.length} of ${entries.length}`)
  L.push('')
  L.push("import type { ModelId } from './catalog'")
  L.push("import type { RoomTypeId } from './rooms'")
  L.push("import type { Wood } from './materials'")
  L.push('')
  L.push('export const GALLERY = [')
  for (const e of tagged) {
    L.push('  {')
    L.push(`    url: ${JSON.stringify(e.url)},`)
    L.push(`    rooms: ${JSON.stringify(e.rooms)},`)
    L.push(`    models: ${JSON.stringify(e.models)},`)
    L.push(`    woods: ${JSON.stringify(e.woods)},`)
    L.push(`    zones: ${JSON.stringify(e.zones)},`)
    if (e.sizes && e.sizes.length) L.push(`    sizes: ${JSON.stringify(e.sizes)},`)
    if (e.note && e.note.trim())   L.push(`    note: ${JSON.stringify(e.note.trim())},`)
    L.push('  },')
  }
  L.push('] as const')
  L.push('')
  return L.join('\n')
}

// Нормализация записи из импортированного JSON или из storage.
// На случай если поля отсутствуют или поломались.
export const normalizeEntry = (x: any, baseUrl = ''): GalleryEntry => ({
  filename: String(x?.filename || ''),
  url:      String(x?.url || joinUrl(baseUrl, x?.filename || '')),
  rooms:    Array.isArray(x?.rooms)  ? x.rooms  : [],
  models:   Array.isArray(x?.models) ? x.models : [],
  woods:    Array.isArray(x?.woods)  ? x.woods  : [],
  zones:    Array.isArray(x?.zones)  ? x.zones  : [],
  sizes:    Array.isArray(x?.sizes)  ? x.sizes  : [],
  note:     typeof x?.note === 'string' ? x.note : '',
  tagged:   !!x?.tagged,
})

// Применение фильтра + поиска к списку записей.
export const applyFilter = (
  arr: GalleryEntry[],
  mode: 'all' | 'untagged' | 'nomodel',
  query: string,
): GalleryEntry[] => {
  let res = arr
  if (mode === 'untagged') res = res.filter(e => !e.tagged)
  if (mode === 'nomodel')  res = res.filter(e => e.models.length === 0)
  if (query.trim()) {
    const q = query.trim().toLowerCase()
    res = res.filter(e => e.filename.toLowerCase().includes(q))
  }
  return res
}
